# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form9(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 350)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 761, 271))
        self.label.setObjectName("label")
        self.Pashalka = QtWidgets.QPushButton(Form)
        self.Pashalka.setGeometry(QtCore.QRect(320, 320, 75, 23))
        self.Pashalka.setObjectName("Pashalka")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(10, 280, 701, 41))
        self.Exit.setObjectName("Exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Программа была написанна при помощи языка програмимирования Python версии 3.9. </span></p><p><span style=\" font-size:12pt;\">Она стабильно работает на этой версии, но так же была протестированна </span></p><p><span style=\" font-size:12pt;\">на версии 3.10 и имеет рабочее состояние на ней. Однако стабильность на этой версии я не </span></p><p><span style=\" font-size:12pt;\">гарантирую. Oc при разработке использовалась Windows. К сожалению на других OC </span></p><p><span style=\" font-size:12pt;\">она не работает. Возможно она запустится на различных графических дистрибутовах Linux </span></p><p><span style=\" font-size:12pt;\">если вы будите использовать различные утилиты, например wine, но при это случае я не </span></p><p><span style=\" font-size:12pt;\">могу вам гарантировать рабочее состояние. Использовались 2 библиотеки - Pillow и PyQt. </span></p><p><span style=\" font-size:12pt;\">Пожалуйста, выполняйте то что скажет вам программа и втом порядке которая она вам </span></p><p><span style=\" font-size:12pt;\">укажет. Программа была созданна Владиславом Горским. Кстати, в этом меню есть пасхалка</span></p></body></html>"))
        self.Pashalka.setText(_translate("Form", "Пасхалка"))
        self.Exit.setText(_translate("Form", "Назад"))
