# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(469, 364)
        self.Nazv = QtWidgets.QLabel(MainWindow)
        self.Nazv.setGeometry(QtCore.QRect(170, -10, 121, 81))
        self.Nazv.setMaximumSize(QtCore.QSize(251, 81))
        self.Nazv.setObjectName("Nazv")
        self.Oprog = QtWidgets.QPushButton(MainWindow)
        self.Oprog.setGeometry(QtCore.QRect(10, 310, 111, 41))
        self.Oprog.setObjectName("Oprog")
        self.Exit = QtWidgets.QPushButton(MainWindow)
        self.Exit.setGeometry(QtCore.QRect(350, 310, 111, 41))
        self.Exit.setObjectName("Exit")
        self.Start = QtWidgets.QPushButton(MainWindow)
        self.Start.setGeometry(QtCore.QRect(160, 130, 151, 81))
        self.Start.setObjectName("Start")
        self.Slogan = QtWidgets.QLabel(MainWindow)
        self.Slogan.setGeometry(QtCore.QRect(130, 50, 201, 41))
        self.Slogan.setObjectName("Slogan")
        self.BDhis = QtWidgets.QPushButton(MainWindow)
        self.BDhis.setGeometry(QtCore.QRect(180, 240, 111, 41))
        self.BDhis.setObjectName("BDhis")
        self.ImWatch = QtWidgets.QPushButton(MainWindow)
        self.ImWatch.setEnabled(True)
        self.ImWatch.setGeometry(QtCore.QRect(150, 310, 181, 41))
        self.ImWatch.setObjectName("ImWatch")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.Nazv.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:20pt;\">PhotoEdit</span></p></body></html>"))
        self.Oprog.setText(_translate("MainWindow", "О программе"))
        self.Exit.setText(_translate("MainWindow", "Выйти"))
        self.Start.setText(_translate("MainWindow", "Начать редактирование"))
        self.Slogan.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Только то, что нужно!</span></p></body></html>"))
        self.BDhis.setText(_translate("MainWindow", "Редактор историй"))
        self.ImWatch.setText(_translate("MainWindow", "Просмотр изображений"))
