# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Met1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(276, 296)
        self.ViborTXT = QtWidgets.QLabel(Form)
        self.ViborTXT.setGeometry(QtCore.QRect(0, 70, 291, 91))
        self.ViborTXT.setObjectName("ViborTXT")
        self.Val1 = QtWidgets.QPushButton(Form)
        self.Val1.setGeometry(QtCore.QRect(20, 140, 121, 31))
        self.Val1.setObjectName("Val1")
        self.Val2 = QtWidgets.QPushButton(Form)
        self.Val2.setGeometry(QtCore.QRect(150, 140, 121, 31))
        self.Val2.setObjectName("Val2")
        self.Val3 = QtWidgets.QPushButton(Form)
        self.Val3.setGeometry(QtCore.QRect(20, 180, 121, 31))
        self.Val3.setObjectName("Val3")
        self.Val4 = QtWidgets.QPushButton(Form)
        self.Val4.setGeometry(QtCore.QRect(150, 180, 121, 31))
        self.Val4.setObjectName("Val4")
        self.Val5 = QtWidgets.QPushButton(Form)
        self.Val5.setGeometry(QtCore.QRect(80, 220, 121, 31))
        self.Val5.setObjectName("Val5")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(80, 260, 121, 31))
        self.Exit.setObjectName("Exit")
        self.NameSohr = QtWidgets.QLineEdit(Form)
        self.NameSohr.setGeometry(QtCore.QRect(10, 60, 261, 31))
        self.NameSohr.setClearButtonEnabled(False)
        self.NameSohr.setObjectName("NameSohr")
        self.pngr = QtWidgets.QRadioButton(Form)
        self.pngr.setGeometry(QtCore.QRect(200, 10, 82, 17))
        self.pngr.setAutoRepeat(False)
        self.pngr.setObjectName("pngr")
        self.jpgr = QtWidgets.QRadioButton(Form)
        self.jpgr.setGeometry(QtCore.QRect(200, 30, 82, 17))
        self.jpgr.setObjectName("jpgr")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 181, 51))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 40, 281, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(-10, 90, 301, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 240, 281, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ViborTXT.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">3.Выберите метод переворота:</span></p></body></html>"))
        self.Val1.setText(_translate("Form", "1. С лева направо"))
        self.Val2.setText(_translate("Form", "2. Сверху вниз"))
        self.Val3.setText(_translate("Form", "3. На 90"))
        self.Val4.setText(_translate("Form", "4. На180"))
        self.Val5.setText(_translate("Form", "5. На 270"))
        self.Exit.setText(_translate("Form", "Назад"))
        self.NameSohr.setText(_translate("Form", "2.Введите имя сохроняемого файла: "))
        self.pngr.setText(_translate("Form", "png"))
        self.jpgr.setText(_translate("Form", "jpg"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">1.Выберете расширение </span></p><p><span style=\" font-size:12pt;\">сохраняемого файла:</span></p></body></html>"))
