# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Met2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 363)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(-50, 290, 451, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ViborTXT = QtWidgets.QLabel(Form)
        self.ViborTXT.setGeometry(QtCore.QRect(110, 110, 171, 21))
        self.ViborTXT.setObjectName("ViborTXT")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 0, 181, 51))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(-10, 90, 421, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-60, 40, 571, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Val3 = QtWidgets.QPushButton(Form)
        self.Val3.setGeometry(QtCore.QRect(30, 180, 171, 31))
        self.Val3.setObjectName("Val3")
        self.jpgr = QtWidgets.QRadioButton(Form)
        self.jpgr.setGeometry(QtCore.QRect(270, 30, 82, 17))
        self.jpgr.setObjectName("jpgr")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(140, 320, 121, 31))
        self.Exit.setObjectName("Exit")
        self.NameSohr = QtWidgets.QLineEdit(Form)
        self.NameSohr.setGeometry(QtCore.QRect(10, 60, 371, 31))
        self.NameSohr.setClearButtonEnabled(False)
        self.NameSohr.setObjectName("NameSohr")
        self.pngr = QtWidgets.QRadioButton(Form)
        self.pngr.setGeometry(QtCore.QRect(270, 10, 82, 17))
        self.pngr.setAutoRepeat(False)
        self.pngr.setObjectName("pngr")
        self.Val4 = QtWidgets.QPushButton(Form)
        self.Val4.setGeometry(QtCore.QRect(210, 180, 171, 31))
        self.Val4.setObjectName("Val4")
        self.Val2 = QtWidgets.QPushButton(Form)
        self.Val2.setGeometry(QtCore.QRect(210, 140, 171, 31))
        self.Val2.setObjectName("Val2")
        self.Val1 = QtWidgets.QPushButton(Form)
        self.Val1.setGeometry(QtCore.QRect(30, 140, 171, 31))
        self.Val1.setObjectName("Val1")
        self.Val8 = QtWidgets.QPushButton(Form)
        self.Val8.setGeometry(QtCore.QRect(210, 260, 171, 31))
        self.Val8.setObjectName("Val8")
        self.Val6 = QtWidgets.QPushButton(Form)
        self.Val6.setGeometry(QtCore.QRect(210, 220, 171, 31))
        self.Val6.setObjectName("Val6")
        self.Val5 = QtWidgets.QPushButton(Form)
        self.Val5.setGeometry(QtCore.QRect(30, 220, 171, 31))
        self.Val5.setObjectName("Val5")
        self.Val7 = QtWidgets.QPushButton(Form)
        self.Val7.setGeometry(QtCore.QRect(30, 260, 171, 31))
        self.Val7.setObjectName("Val7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ViborTXT.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">3.Выберите опцию:</span></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">1.Выберете расширение </span></p><p><span style=\" font-size:12pt;\">сохраняемого файла:</span></p></body></html>"))
        self.Val3.setText(_translate("Form", "3. Подчёркивание границ"))
        self.jpgr.setText(_translate("Form", "jpg"))
        self.Exit.setText(_translate("Form", "Назад"))
        self.NameSohr.setText(_translate("Form", "2.Введите имя сохроняемого файла: "))
        self.pngr.setText(_translate("Form", "png"))
        self.Val4.setText(_translate("Form", "4. Рельеф"))
        self.Val2.setText(_translate("Form", "2. Детализация"))
        self.Val1.setText(_translate("Form", "1. Блюр"))
        self.Val8.setText(_translate("Form", "8. Повышение резкости"))
        self.Val6.setText(_translate("Form", "6. Сглаживание"))
        self.Val5.setText(_translate("Form", "5. Сильн.подчёркивание границ"))
        self.Val7.setText(_translate("Form", "7. Сильное сглаживание"))
