# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Met3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(291, 209)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 150, 311, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 40, 311, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(-10, 90, 331, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pngr = QtWidgets.QRadioButton(Form)
        self.pngr.setGeometry(QtCore.QRect(210, 10, 82, 17))
        self.pngr.setAutoRepeat(False)
        self.pngr.setObjectName("pngr")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(90, 170, 121, 31))
        self.Exit.setObjectName("Exit")
        self.NameSohr = QtWidgets.QLineEdit(Form)
        self.NameSohr.setGeometry(QtCore.QRect(20, 60, 251, 31))
        self.NameSohr.setClearButtonEnabled(False)
        self.NameSohr.setObjectName("NameSohr")
        self.jpgr = QtWidgets.QRadioButton(Form)
        self.jpgr.setGeometry(QtCore.QRect(210, 30, 82, 17))
        self.jpgr.setObjectName("jpgr")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 181, 51))
        self.label.setObjectName("label")
        self.Val1 = QtWidgets.QPushButton(Form)
        self.Val1.setGeometry(QtCore.QRect(10, 120, 271, 41))
        self.Val1.setObjectName("Val1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 151, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pngr.setText(_translate("Form", "png"))
        self.Exit.setText(_translate("Form", "Назад"))
        self.NameSohr.setText(_translate("Form", "2.Введите имя сохроняемого файла: "))
        self.jpgr.setText(_translate("Form", "jpg"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">1.Выберете расширение </span></p><p><span style=\" font-size:12pt;\">сохраняемого файла:</span></p></body></html>"))
        self.Val1.setText(_translate("Form", "Нахождение границ с их выделением и тиснением"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">3. Выберете метод:</span></p></body></html>"))
