# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Met4.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(228, 201)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 151, 20))
        self.label_2.setObjectName("label_2")
        self.Val1 = QtWidgets.QPushButton(Form)
        self.Val1.setGeometry(QtCore.QRect(50, 120, 141, 31))
        self.Val1.setObjectName("Val1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 211, 51))
        self.label.setObjectName("label")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(60, 160, 121, 31))
        self.Exit.setObjectName("Exit")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(-10, 90, 331, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.NameSohr = QtWidgets.QLineEdit(Form)
        self.NameSohr.setGeometry(QtCore.QRect(10, 60, 211, 31))
        self.NameSohr.setClearButtonEnabled(False)
        self.NameSohr.setObjectName("NameSohr")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 40, 311, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(-30, 140, 311, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">2. Выберете метод:</span></p></body></html>"))
        self.Val1.setText(_translate("Form", "Скругление изображения"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Возможно сохранить </span></p><p><span style=\" font-size:12pt;\">изображение только в png</span></p></body></html>"))
        self.Exit.setText(_translate("Form", "Назад"))
        self.NameSohr.setText(_translate("Form", "1.Введите имя сохроняемого файла: "))
