# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Met6.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form6(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(306, 458)
        self.ViborTXT = QtWidgets.QLabel(Form)
        self.ViborTXT.setGeometry(QtCore.QRect(10, 230, 291, 91))
        self.ViborTXT.setObjectName("ViborTXT")
        self.NameSohr = QtWidgets.QLineEdit(Form)
        self.NameSohr.setEnabled(True)
        self.NameSohr.setGeometry(QtCore.QRect(20, 60, 261, 31))
        self.NameSohr.setMouseTracking(True)
        self.NameSohr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.NameSohr.setClearButtonEnabled(False)
        self.NameSohr.setObjectName("NameSohr")
        self.Val5 = QtWidgets.QPushButton(Form)
        self.Val5.setGeometry(QtCore.QRect(90, 380, 121, 31))
        self.Val5.setObjectName("Val5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 0, 221, 51))
        self.label.setObjectName("label")
        self.Val3 = QtWidgets.QPushButton(Form)
        self.Val3.setGeometry(QtCore.QRect(10, 340, 131, 31))
        self.Val3.setObjectName("Val3")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(-20, 400, 341, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(90, 420, 121, 31))
        self.Exit.setObjectName("Exit")
        self.Val4 = QtWidgets.QPushButton(Form)
        self.Val4.setGeometry(QtCore.QRect(150, 340, 141, 31))
        self.Val4.setObjectName("Val4")
        self.Val1 = QtWidgets.QPushButton(Form)
        self.Val1.setGeometry(QtCore.QRect(10, 300, 131, 31))
        self.Val1.setObjectName("Val1")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 90, 311, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Val2 = QtWidgets.QPushButton(Form)
        self.Val2.setGeometry(QtCore.QRect(150, 300, 141, 31))
        self.Val2.setObjectName("Val2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 40, 321, 31))
        self.line.setMouseTracking(True)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(-10, 240, 341, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.ViborTXT_2 = QtWidgets.QLabel(Form)
        self.ViborTXT_2.setGeometry(QtCore.QRect(10, 100, 291, 101))
        self.ViborTXT_2.setObjectName("ViborTXT_2")
        self.VaterMark = QtWidgets.QPushButton(Form)
        self.VaterMark.setGeometry(QtCore.QRect(10, 200, 281, 51))
        self.VaterMark.setObjectName("VaterMark")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ViborTXT.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">3.Выберите место размещения:</span></p></body></html>"))
        self.NameSohr.setText(_translate("Form", "1.Введите имя сохроняемого файла: "))
        self.Val5.setText(_translate("Form", "5. По середине"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Поддерживается только</span></p><p><span style=\" font-size:12pt;\">формат png для сохранения</span></p><p><br/></p></body></html>"))
        self.Val3.setText(_translate("Form", "3. Правый верхний угол"))
        self.Exit.setText(_translate("Form", "Назад"))
        self.Val4.setText(_translate("Form", "4. Правый нижний угол"))
        self.Val1.setText(_translate("Form", "1. Верхний леый угол"))
        self.Val2.setText(_translate("Form", "2. Левый нижний угол"))
        self.ViborTXT_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">2.Выберите водяной знак</span></p><p><span style=\" font-size:14pt;\">(поддерживается только формат</span></p><p><span style=\" font-size:14pt;\">png):</span></p></body></html>"))
        self.VaterMark.setText(_translate("Form", "Нажмите что бы выбрать водяной знак"))
