# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Met7.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form7(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 375)
        self.Val7 = QtWidgets.QPushButton(Form)
        self.Val7.setGeometry(QtCore.QRect(30, 290, 171, 31))
        self.Val7.setObjectName("Val7")
        self.Val2 = QtWidgets.QPushButton(Form)
        self.Val2.setGeometry(QtCore.QRect(210, 170, 171, 31))
        self.Val2.setObjectName("Val2")
        self.NameSohr = QtWidgets.QLineEdit(Form)
        self.NameSohr.setGeometry(QtCore.QRect(10, 60, 391, 31))
        self.NameSohr.setClearButtonEnabled(False)
        self.NameSohr.setObjectName("NameSohr")
        self.Val6 = QtWidgets.QPushButton(Form)
        self.Val6.setGeometry(QtCore.QRect(210, 250, 171, 31))
        self.Val6.setObjectName("Val6")
        self.Val4 = QtWidgets.QPushButton(Form)
        self.Val4.setGeometry(QtCore.QRect(210, 210, 171, 31))
        self.Val4.setObjectName("Val4")
        self.Val8 = QtWidgets.QPushButton(Form)
        self.Val8.setGeometry(QtCore.QRect(210, 290, 171, 31))
        self.Val8.setObjectName("Val8")
        self.ViborTXT = QtWidgets.QLabel(Form)
        self.ViborTXT.setGeometry(QtCore.QRect(30, 100, 341, 61))
        self.ViborTXT.setObjectName("ViborTXT")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-50, 40, 571, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Val3 = QtWidgets.QPushButton(Form)
        self.Val3.setGeometry(QtCore.QRect(30, 210, 171, 31))
        self.Val3.setObjectName("Val3")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(-80, 320, 571, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pngr = QtWidgets.QRadioButton(Form)
        self.pngr.setGeometry(QtCore.QRect(280, 10, 82, 17))
        self.pngr.setAutoRepeat(False)
        self.pngr.setObjectName("pngr")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 0, 181, 51))
        self.label.setObjectName("label")
        self.Val1 = QtWidgets.QPushButton(Form)
        self.Val1.setGeometry(QtCore.QRect(30, 170, 171, 31))
        self.Val1.setObjectName("Val1")
        self.jpgr = QtWidgets.QRadioButton(Form)
        self.jpgr.setGeometry(QtCore.QRect(280, 30, 82, 17))
        self.jpgr.setObjectName("jpgr")
        self.Val5 = QtWidgets.QPushButton(Form)
        self.Val5.setGeometry(QtCore.QRect(30, 250, 171, 31))
        self.Val5.setObjectName("Val5")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(-80, 90, 501, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Exit = QtWidgets.QPushButton(Form)
        self.Exit.setGeometry(QtCore.QRect(140, 340, 121, 31))
        self.Exit.setObjectName("Exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Val7.setText(_translate("Form", "7. BGR"))
        self.Val2.setText(_translate("Form", "2. G"))
        self.NameSohr.setText(_translate("Form", "2.Введите имя сохроняемого файла: "))
        self.Val6.setText(_translate("Form", "6. BRG"))
        self.Val4.setText(_translate("Form", "4. GBR"))
        self.Val8.setText(_translate("Form", "8. RBG"))
        self.ViborTXT.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">3.Выберите какой RGB канал извлечь</span></p><p><span style=\" font-size:14pt;\">или изменить последовательность:</span></p></body></html>"))
        self.Val3.setText(_translate("Form", "3. B"))
        self.pngr.setText(_translate("Form", "png"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">1.Выберете расширение </span></p><p><span style=\" font-size:12pt;\">сохраняемого файла:</span></p></body></html>"))
        self.Val1.setText(_translate("Form", "1. R"))
        self.jpgr.setText(_translate("Form", "jpg"))
        self.Val5.setText(_translate("Form", "5. GRB"))
        self.Exit.setText(_translate("Form", "Назад"))
